// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function IsRunning() {
  return window['go']['app']['App']['IsRunning']();
}

export function LoadConfig(arg1) {
  return window['go']['app']['App']['LoadConfig'](arg1);
}

export function RunBacktest(arg1) {
  return window['go']['app']['App']['RunBacktest'](arg1);
}

export function SelectConfigFile() {
  return window['go']['app']['App']['SelectConfigFile']();
}

export function StartBot(arg1) {
  return window['go']['app']['App']['StartBot'](arg1);
}

export function StopBot() {
  return window['go']['app']['App']['StopBot']();
}
