// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {config} from '../models';

export function GetState():Promise<app.StateSnapshot>;

export function IsRunning():Promise<boolean>;

export function LoadConfig(arg1:string):Promise<config.Config>;

export function RunBacktest(arg1:app.BacktestRequest):Promise<app.BacktestResult>;

export function SelectConfigFile():Promise<string>;

export function StartBot(arg1:config.Config):Promise<void>;

export function StopBot():Promise<void>;
